# Site Settings
title: A Data Science Odyssey
description: Embark on a Journey of Data Exploration, Analysis, and Visualization
show_downloads: true
remote_theme: jekyll-theme-midnight

# Author Information
author:
  name: Bhagyashree KS Bhat
  email: bshreeks@gmail.com
  bio: Data Scientist

# Social Media Links
social:
  - name: Website
    url: http://datayogi.unaux.com/
  - name: LinkedIn
    url: https://www.linkedin.com/in/bhagyashreeks/
