# Example _config.yml file for a GitHub Pages site

# Site Settings
title: My Portfolio
description: A showcase of my projects and skills
theme: jekyll-theme-midnight

# Author Information
author:
  name: Bhagyashree KS Bhat
  email: bshreeks@gmail.com
  bio: Data Scientist

# Social Media Links
social:
  - name: Website
    url: http://datayogi.unaux.com/
  - name: LinkedIn
    url: https://www.linkedin.com/in/bhagyashreeks/

# Navigation Links
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: About
    url: /about
  - title: Contact
    url: /contact
