# Site Settings
title: A Data Science Odyssey
description: Embark on a Journey of Data Exploration, Analysis, and Visualization
profile_picture: /assets/images/PP2.jpg
show_downloads: false
theme: jekyll-theme-tactile

# Author Information
author:
  name: Bhagyashree KS Bhat
   avatar: /assets/images/PP2.jpg
  email: bshreeks@gmail.com
  bio: Data Scientist

# Social Media Links
social:
  - name: Website
    url: http://datayogi.unaux.com/
  - name: LinkedIn
    url: https://www.linkedin.com/in/bhagyashreeks/
